### ISSUE TITLE
0. Orientation

### ISSUE THREAD

**Issue by JustKode** [Dcom-KHU/cpp-to-java#1]
[강의 자료](https://justkode.kr/java/cpp-to-java-0)
아래 이슈에 답글로 5줄 요약을 남겨 주세요.

**Comment by ohbrent** [comment]
자바는 범용성이 좋다!

**Comment by splguyjr** [comment]
자바는 JVM을 이용하여 이를 지원하는 어느 운영체제에서도 실행이 가능
C++에 비해 종속성이 덜함, 가비지 컬렉터가 존재한다는 장점
그러나 C++에 비해 느리고, 코드가 길고 예외 처리에 있어 까다롭다는 단점
파일을 만들 때 파일 명과 public class의 이름이 일치할 수 있도록 약속
public static void main(String args[])는 C++에서 int main()역할을 함

**Comment by kevinlim17** [comment]
- Java는 이식성이 좋고(운영체제에 대한 종속성이 덜하고), 가비지 콜렉터가 존재해 메모리 관리를 따로 하지 않아도 된다.
-  그러나 C++에 비해 평균적으로 코드가 길다는 점, 가비지 콜렉터의 존재로 인해 상대적으로 느리다는 점이 단점이다.
- JRE는 자바 프로그램을 실행하기 위해 필요한 '환경'이고, JDK는 .java 파일을 컴파일하는 데 쓰이는 Kit이다. JDK는 JRE를 포함한다.
- Java에서 public static void main(String[] args)는 C++에서 int main()과 같은 역할을 한다.
- .java 파일의 이름은 코드의 public class(코드 상에서 유일하게 존재)의 이름과 동일해야 한다.

**Comment by ohbrent** [comment]
* 자바는 가비지 컬렉터가 있으며 메모리 관리 코드를 넣지 않아도 된다는 장점이 있지만, 그런 기능이 있는 만큼 c++에 비해서는 상대적으로 느리다는 단점이 있다. 또한 코드가 길며 예외 처리가 까다롭다.
* public 클라스는 단 하나만이 존재해야 하며 (가독성 때문에) 이것 안에 있는 public static void main(String args[]) 는 c++ 에서 int main()역할을 한다.
* 자바는 c++의 단점인 종속성 문제를 해결하기 위해 태어났다. 이 문제 컴파일이 된 코드가 하나의 플랫폼에서만 작동하는 문제를 일컫는다.
* 자바는 unsigned를 적용할 수 없다.
* 자바는 한국의 코딩 시장을 점령하고 있다 (가장 중요!)

**Comment by choi5798** [comment]
1. 자바는 JVM을 통해 운영체제의 영향을 크게 받지 않는다
2. 자바는 가비지 컬렉터가 존재하여 메모리 관리를 c++처럼 하지 않아도 된다. 그만큼 c++ 보다는 속도가 느리다는 단점이 있다.
3. 자바로 만들어진 프로그램을 실행하려면 JRE만 있어도 되지만 자바로 개발을 하려면 JDK가 있어야 한다. 즉, JDK 안에 JRE가 포함되어 있다.
4. java파일의 이름은 public class 이름과 동일해야 하고 만약 public class가 존재하지 않는다면 아무 클래스 중 하나와만 이름이 동일하면 된다.
5. c++의 main함수의 역할을 하는 것이 public static void main(String[] args)이다. 자바 파일을 실행시키면 이 main함수가 실행된다.

**Comment by Vanilla-js-c** [comment]
- 객체지향 프로그래밍에 용이한 구조를 가지고 있으며 코드의 구조가 유사하다는 점에서 C++과 닮은 구석이 많다.
- JVM(자바 가상 머신)을 이용해 같은 코드로 많은 운영체제에서 실행 가능하게 한다(이식성이 좋다)
- 가비지 컬렉터의 존재로 메모리 관리가 용이하며, 다양한 자료가 있다는 장점이 있다. 그러나 실행이 느리고 코드가 길며 예외 처리가 까다롭다는 단점이 있다.
- JRE는 자바 프로그램을 실행하기 위해 필요한 패키지이며 JDK는 자바 코드를 컴파일 하는 데 사용한다.
- public class와 파일명이 일치해야 하며 main함수가 public class 내부에 존재한다.

**Comment by Light-Island** [comment]
1. Java는 C++에 비해 종속성 문제가 덜하고, 가비지 콜렉터를 이용해 메모리 할당에 더 유용하다.
2. Java Code를 JAVAC 컴파일러를 통해 class 파일로 바꾸고, 이를 JVM 위에 올려 실행한다.
3. JRE(Java Runtime Environment)는 자바 프로그램 실행을 위한 패키지이며, JDK(Java Development Kit)은 자바 코드를 컴파일 하는데 사용한다.
4. C++에서 int main() 역할을 자바에선 public static void main(String args[])이다.
5. 가독성을 위해 public class를 이용하는데, 파일 내에서 하나만 존재해야하며, 파일명과 완전히 일치해야한다.

**Comment by HYEOK9** [comment]
- 실무에서 많이 씀
- 객체지향
- multi thread 지원
- garbage collector로 자동 메모리 관리
- JVM에서 돌아가기 때문에 OS와 독립적

**Comment by nahyun0121** [comment]
- C++과 Java는 닮은 점이 많다. (객체지향 프로그래밍에 용이한 구조, 코드 구조가 상당히 유사하다 등)
- Java가 C++보다 좋은 점: 운영체제 종속성이 덜 함. 많은 사람들이 사용하는 만큼, 자료가 다양함.
- Java가 C++보다 나쁜 점: 느리고 코드가 긺. 예외 처리의 까다로움
- JRE: Java Runtime Environment의 약자. 자바 프로그램을 실행하기 위해 필요한 패키지 실행 환경.
- JDK: Java Development Kit의 약자. 자바 코드를 컴파일 하는 데 사용하는 javac를 포함함. (JRE도 포함함)
- Java에서 파일명은, public class 이름과 완전히 일치해야 한다. 또한, public class는 파일 내에 하나만 존재해야 한다.
