### ISSUE TITLE
1. System Class

### ISSUE THREAD

**Issue by JustKode** [Dcom-KHU/cpp-to-java#3]
[강의 자료](https://justkode.kr/java/cpp-to-java-1)
아래 이슈에 답글로 5줄 요약을 남겨 주세요.

**Comment by choi5798** [comment]
Scanner.nextLine()은 줄 단위로 입력을 받아 개행문자('\n') 까지도 한 번에 처리하지만
Scanner.next()는 공백을 단위로 입력을 받아 사용자의 입력을 다 받아도 마지막에
개행문자가 남아있을 수 있다.

배열을 반복문으로 직접 복사할 수도 있지만 System.arraycopy()라는 메소드로 편하게 복사가 가능하다

주요 입출력 메서드들은 System 클래스에 있고 System 클래스는 java.lang 패키지에 포함되어 있다

java.lang 패키지는 import를 직접 하지 않아도 그 안에 있는 메서드들을 자유롭게 사용할 수 있다
따라서 주요 입출력 또한 import 없이 실행할 수 있다

Scanner로 입력을 받으면 String형태로 반환이 되고 필요한 자료형에 맞게 형변환을 할 수 있다.
예를 들어, Integer.parseInt(), Double.parseDouble() 등이 있다.

**Comment by kevinlim17** [comment]
- System Class는 JVM을 거쳐 OS의 일부 기능을 사용할 수 있도록 하고, 모든 Method가 Static으로 이루어져 있어 객체 생성 없이 모든 Method를 이용할 수 있다.
- C++의 OutputStream의 개념과 동일하게 Java에서는 PrintStream이 존재한다. (InputStream, FileStream도 마찬가지)
- PrintStream의 Method들 중 public void print(Object obj)와 public void println(Object obj)는 개행 포함 여부에서 차이가 있고, public void printf(Object format, Object obj1, Object obj2, ...)와 public void format()은 입력 파라미터의 형식과 Method의 기능이 동일하다.
- System.in을 이용해 데이터를 입력받으려면, Scanner Class를 import java.util.*; 을 이용해 import한 뒤, new Scanner(System.in)을 통해 scanner 객체를 할당 받아야 한다.
- 반복문을 사용하는 대신 System Class의 static void arraycopy(Object src, int srcPos, Object dest, int destPos, int length)라는 메소드로 편하게 배열 복사가 가능하다.

**Comment by nahyun0121** [comment]
- System Class는 JVM을 거쳐 운영체제의 일부 기능을 사용할 수 있도록 도와주는 클래스로, 객체 생성 없이 모든 메서드를 사용할 수 있다.
- System Class로 입출력하기
1. System.out: C++에서 OutputStream 역할
2. System.in: C++에서 InputStream 역할

- System Class Method
1. static void arraycopy(Object src, int srcPos, Object dest, int destPos, int length): 배열 src를 srcPos 자리부터 하여 배열 dest의 destPos 자리부터 length 크기만큼 복사한다.
2. static long currentTimeMills(): 1970/1/1 자정부터 현재까지의 시간을 밀리초로 반환.
3. static void gc(): 가비지 컬렉션 실행. (프로그램이 무거워질 것 같을 때)
3. static String getPropertys(): 시스템 환경 변수 목록을 얻어온다.
4. static void setProperty(String key, String value): 시스템 환경변수에 key와 그에 따른 value를 할당한다.
5. static void exit(int status): 현재 수행 중인 응용 프로그램을 종료시킨다.

**Comment by Chae-Js** [comment]
1. System Class 는 java.lang 패키지에 속한 class로 System Class는 JVM을 거쳐 운영체제의 일부 기능을 사용하게 해주며, 모든 메서드가 Static으로 이뤄져 객체 생성 없이 메서드를 사용가능하다.
2. C++의 InputStream, OutputStream, FileStream과 비슷하게 Java에는 InputStream, PrintStream, FileInputStream, FileOutputStream이 존재한다. 
3. Java에서 PrintStream을 통해 출력이 가능하고 여기에는 public void print(Object obj), public void println(Object obj) 등의 메서드가 있다.
4. System.in은 Java에서 C++의 InputStream과 일치한다. 이를 통해 데이터를 받으려면 Scanner 객체를 할당받아야 한다.
5.  System 객체 내부에는 arraycopy 메서드를 통해 배열의 복사가 가능하다.

**Comment by ohbrent** [comment]
1. java.lang 패키지는 자바 프로그래밍에 사용되는 가장 기본적인 class들을 모아 놓은 패키지이고, 호출 없이 사용 가능하다. 또한 우리가 자주 사용할 Syetem class를 포함하고 있다. Syetem class는 모든 메서드가 Static으로 이루어져 있다는 특징이 있으며, 객체 생성 없이도 모든 메서드를 사용할 수 있다.

2. System.out에 대하여, 저것은 곧 java.io.PrintStream이다. PrintStream은 c++의 cout역할을 담당하고 있으며 이것의 메소드들에는 크게 다음과 같이 있다.
-print()  :   괄호 안의 것을 개행 없이 출력
-println()  :  괄호 안의 것을 개행과 함께 출력
-printf()  :  첫 번째 파라미터로 들어간 포맷에 맞게 , 다른 파라미터들을 포맷에 맞게 출력
-format() :  printf와 동일

3. System.in에 대하여, 저것은 java.io.BufferedInputStream 객체를 가지며 c++의 InputStream과 일치한다. System.in을 이용하여 입력을 받으려면 Scanner 객체를 이용해야 한다.import java.util.*; 을 해준 후  Scanner scanner = new Scanner(System.in); 을 해주면 Scanner 객체를 할당 받을 수 있다. 이후 nextLine(), next(),nextInt() 등으로 입력 받을 수 있다.

4.try,catch 문법으로 오류에 대한 예외 처리도 할 수 있다.

5. 이 외의 System 클래스의 메소드이다.
- arraycopy() : 파라미터로 들어간 배열 중 정해진 구간 만큼의 요소를 또 다른 배열에 대입한다.
- currentTimeMills() : 1970/1/1 자정부터 지금 까지의 시간을 밀리초로 반환
- getPropertys() : 시스템 환경변수 테이블을 가지고 옴
- setPropertys() : 시스템 환경변수 테이블의 key에 value를 할당
- exit() : 파라미터에 들어간 값을 반환 후, 프로그램을 종료

**Comment by splguyjr** [comment]
1.java.lang 패키지는 Java 프로그래밍에 사용되는 가장 기본적인 Class들을 모아놓은 패키지로 import하지 않아도 사용가능함. 이에 속하는 System Class는 모든 메서드가 Static으로 이루어져 있어 객체 생성없이도 모든 메서드를 사용 할 수 있음.

2.System.out -> getClass().getName()을 통해 알아보면 java.io.PrintStream임을 알 수 있음. 
PrintStream의 메서드로는 (앞에 public void) print(), printIn(),printf(),format()등 이 있다.

3.System.in -> java.io.BufferedInputStream 객체를 가짐. 이는 입력을 담당하는 객체
Scanner -> import java.util.*;을 통해 import할 수 있고
Scanner scanner = new Scanner(System.in);와 같이 객체를 할당받는다.
scanner.next(), nextLine()등으로 입력받은후 Integer.parseInt(string), Float.parseFloat(string)을 통해 각각 int float형으로 변환가능하다.

4.try catch구문을 통한 예외상황에 대한 처리
try{ }
catch (NumberFormatException e) {}의 형태로 정수가 입력되지않았을 경우 처리가능.

5.System Methods
stataic void arraycopy(Object src, int srcPos, Object dest, int destPos, int length);->배열복사
이외에도 다양하게 존재

**Comment by Light-Island** [comment]
1. Java.lang 패키지에 있는 System class는 JVM을 거쳐 운영체제의 일부 기능을 사용할 수 있게 해주는 class이며, 모든 method가 static으로 이루어져 있어 객체 생성 없이 method를 사용할 수 있다.

2. System.out의 class 이름은 java.io.PrintStream이며,  C++의 cout 역할을 하는것이 Java의 PrintStream이다.
System.in의 class 이름은 java.io.BuffedInputStream이며, C++의 cin 역할을 하는것이 Java의 InputStream이다.

3. PrintStream의 method들은 파라미터값을 개행 없이 출력하는 print, 파라미터값을 개행 포함 출력하는 println, 파라미터들을 포맷에 맞게 출력하는 printf, format이 있다.

4.Java.util에 있는 scanner을 이용해 입력을 받을 수 있다. scanner.nextline()을 이용해 string형을, 이를 Integer.parseInt(string), Float.parseFloat(string)을 이용해 각각 int형, float형으로 변환해서 입력받는다.

5.System method들 중에서는 배열 전체를 복사할 수 있는 static void arraycopy(Object srcPos, Object destPos, int length), 가비지 컬렉션을 실행하는 static void gc(), 시스템 환경변수 테이블을 가져오는 static Properties getPropertys() 등이 있다.

**Comment by cherrie-k** [comment]
- java.lang 패키지는 import 없이 사용 가능하며 이 안에 있는 System Class는 모든 메서드가 static이라 객체 생성 없이 사용 할 수 있다.

- System.out은 java.io.PrintStream이고 (public void) print(), println(), printf(), format() 등이 있다. c++의 cout 역할.

- 입력을 담당하는 System.in은 java.io.BufferedInputStream이고 c++의 InputStream역할. 입력을 받기 위해서는 Scanner Class를 이용해야 함.

- try, catch를 이용해서 오류에 대한 예외도 다룰 수 있다. NumberFormatException을 이용해서 parseInt, parseFloat에 대한 에러도 다룰 수 있음

- System 객체 내부의 메서드로는 arraycopy(), currentTimeMills(), getPropertys(), setPropertys, exit() 등이 있다. 순서대로 배열 복사 후 대입, 시간 변환, 시스템 환경변수 테이블 가져오고 할당, 프로그램 종료의 역할을 한다.

**Comment by HYEOK9** [comment]
- System Class : 는 JVM을 거쳐 운영체제의 일부 기능을 사용 할 수 있도록 도와주는 클래스. 객체 생성 없이 모든 메서드를 사용가능
- java.lang 패키지: Java 프로그래밍에 사용 되는 가장 기본적인 Class들을 모아놓은 패키지, 기본적으로 사용 가능
- java에서의 출력 
1.print - 개행없이 출력
2.println - 개행과함께 출력
3.printf, fomat - 포맷에 맞게 출력
- java에서의 입력은 Scanner scan=new Scanner(System.in)을 통해서 함.
1. scan.nextLine() - String으로 받음
2. scan.next() - 공백기준으로 받음
3. scan.nextInt() - 정수를 입력받음
- System.gc(); 를 통해 garbage collection 실행
