### ISSUE TITLE
2. OOP

### ISSUE THREAD

**Issue by JustKode** [Dcom-KHU/cpp-to-java#5]
[강의 자료](https://justkode.kr/java/cpp-to-java-1)
아래 이슈에 답글로 5줄 요약을 남겨 주세요.

**Comment by choi5798** [comment]
static 제어자는 해당 클래스로 생성된 모든 인스턴스들이 공유하는 값이다. 즉, 같은 타입의 객체라면
한 객체에서 static 값을 변경했을 때 다른 객체에도 그 값이 변경된다.

final 제어자는 변경 될 수 없다는 뜻. 클래스는 조상 클래스가 될 수 없고 메서드는 오버라이딩
될 수 없고 변수는 상수가 된다.

abstract 제어자는 객체 앞에 붙어 해당 객체가 추상객체라는 것을 의미한다.
즉, 선언부만 작성하고 인스턴스는 객체 및 메서드를 상속받거나 오버라이딩하여
생성하여야 한다.

4개의 접근 제어자 중 private은 같은 클래스 내에서만, protected는 자손 클래스까지, default는 해당 패키지 내에서까지만
접근 가능하고 public은 접근 제한이 없다.

클래스의 생성자를 만들지 않았을 경우 기본 생성자를 부르지만 임의의 생성자를 만든 순간
기본 생성자가 사라지기 때문에 필요한 경우에 대해 생성자 오버로딩을 해줘야 한다.

**Comment by kevinlim17** [comment]
- private:과 public: 그리고 protected:를 이용해 제한자를 적용하는 C++과 다르게, Java에서는 Class 자체나 Class의 Member에 접근 제어자를 부여한다.
- C++처럼 대입을 이용한 복사 대신, Java에서는 Class 내에서 Copy Constructor를 만들어 new Class(Class c)를 사용해 객체의 복사가 가능하다.
- Static 제어자를 이용해 Class 메모리에 변수를 만들어, 생성된 인스턴스의 갯수를 파악하고 Const Variable을 생성할 수 있다.
- Final 제어자가 붙은 Class는 부모 Class가 될 수 없고, Method는 파생 Class에서 Override할 수 없으며, Global/Local Variable 모두 상수가 된다.
- Abstract 제어자는 미완성의 의미를 가지고 있으며, Abstract Class는 인스턴스를 생성할 수 없다. Abstract Class와 Method를 사용하기 위해선 Abstract Class의 파생 Class에서 Abstract Method를 Override해야 한다.
- Initialization Block의 종류에는 Class 변수를 초기화하는 클래스 초기화 블록(static 제어자와 중괄호를 이용해 작성)과 Object의 변수를 초기화하는 인스턴스 초기화 블록(중괄호만을 이용해 작성)이 있다.  두 Block 모두 생성자보다 앞서 실행되며, 클래스 초기화 블록은 Class가 메모리에 로드될 때 한 번만 실행된다.

**Comment by Chae-Js** [comment]
1.  Java에서는 Class의 멤버 함수, 변수 각각 private, public 등을 적용한다. 그 외에는 c++과 유사하다.
2.  static 제어자는 Static 변수, 함수를 만들 수 있다. 이는 객체 메모리가 아닌, 클래스 메모리에 있는 변수이며 생성된 인스턴스 갯수 확인 등에 사용된다.
3. final 제어자는 클래스, 메서드, 멤버변수, 지역변수에 적용되는 변경 될 수 없다는 의미의 제어자이다.(C++의 const와 유사)
4. abstract 제어자는 미완성의 의미를 지닌다. 추상메서드 선언에 사용되며 이를 사용하기 위해서는 추상 클래스의 파생클래스에서 메서드를 오버라이딩 해야 한다.
5. 초기화 블럭은 클래스 초기화 블럭, 인스턴스 초기화 블럭으로 나뉜다. 클래스 초기화 블럭은 static 제어자와 중괄호로, 인스턴스 초기화 블럭은 중괄호 만을 이용해 작성한다.

**Comment by ohbrent** [comment]
1. C++ 과 다르게 java 에서는 private,public 등을  멤버 함수 / 변수 하나하나 전부 적용한다. 이를 적용하지 않는다면 아무런 기능을 하지 않는 기본 생성자가 만들어진다. 

2. this 와 new Class(Class c)를 이용하면 복사 생성자의 역할을 할 수 있도록 할 수 있다.

3. static 변수는 클래스 메모리에 있는 변수이다. 다음과 같은 경우에 사용된다.
-생성된 인스턴스 개수 확인
-Const variable 설정
-유틸 함수를 제공하는 Class를 만들고자 할 때


4. final는 c++의 const과 유사하며 클래스, 메서드, 멤버변수, 지역변수에 적용이 가능하다.

5. abstract 은 c++ virtual과 유사하며 이를 이용하여 만든 추상메서드를 만들 수 있고, 해당 클래스는 추상 클래스가 된다.

6. 접근 제어자 중 default (제어자 입력 하지 않는 경우) 는 같은 패키지 내에서만 접근이 가능한 경우이다.

7. 클래스 초기화 블럭은 static 제어자와 중괄호를 이용하여 작성하고, 인스턴스 초기화 블럭은 중괄호만을 이용하여 작성한다. 
인스턴스 초기화 블럭은 생성자보다 먼저 호출되고 클래스 초기화 블럭은 클래스가 메모리에 처음 로딩 될 때, 한 번만 실행된다.

**Comment by cherrie-k** [comment]
- Java에서 class를 만드는건 대부분 C++과 유사하지만, 멤버 함수나 변수를 선언 할때마다 private/public을 하나하나 지정 해줘야 한다는 차이가 있다.

- new Class(Class c)가 복사 생성자의 역할을 한다. C++과 다르게 대입을 이용한 복사를 수행 할 수는 없지만 this를 이용해 생성자 재사용은 가능하다.

- 제어자는 클래스/변수/메소드에 부가적인 의미를 부여하고 static, final, abstract이 있다. + 접근 제어자..

- static변수는 클래스 메모리에 있는 변수라 생각 (객체 메모리x)

- final 제어자는 const처럼 변경 될 수 없다. 조상 클래스X, 오버라이딩X, 값변경X.

- abstract제어자는 virtual같은거라 선언부만 작성하고 실제 수행 내용은 구현하지 않는 추상 메서드를 선언할때 사용. interface 등에 쓰인다.

- 초기화 블럭(initialization block)을 통해 클래스와 인스턴스를 초기화해줄수 있고, 이는 생성자보다도 먼저 호출된다.

**Comment by nahyun0121** [comment]
- C++와는 달리, Java에서는 클래스를 만들 때 멤버 함수, 멤버 변수 하나하나에 private, public을 적용한다. 그리고 같은 패키지 내에 존재한다면, 굳이 import 하지 않아도 된다.
- 생성자를 작성하지 않으면 기본 생성자가 만들어진다. copy constructor도 this를 이용하여 만들 수 있다.
- static 제어자는 생성된 인스턴스 개수 확인, 상수 변수 설정, 유틸 함수를 제공하는 클래스를 만들고자 할 때 등에서 사용된다.
- final 제어자는 클래스, 메서드, 멤버 변수, 지역 변수에 적용할 수 있으며 '변경될 수 없다'는 의미를 지니고 있다.
- abstract 제어자는 메서드와 클래스에 적용할 수 있으며 '미완성'이라는 의미를 지닌다.
- 초기화 블럭(생성자보다 먼저 호출됨.): 
1. 클래스 초기화 블럭 - 클래스 내에 작성하며 한 번만 실행된다. 클래스 변수 초기화.
2. 인스턴스 초기화 블럭 - 중괄호만을 이용하여 작성한다. 객체의 변수 초기화.

**Comment by Light-Island** [comment]
1. Java에서는 class안의 멤버 변수와 함수 각각에 private과 public을 지정해 줘야 한다. 또한 this를 이용해 객체 자신의 멤버 변수에 접근할 수 있다.

2. new Class(Class c)를 통해 복사 생성자를 만들고, this를 이용해 객체의 복사가 가능해진다.

3. static 변수는 class 메모리에 있는 변수이며, static 제어자를 통해 생성된 instance 개수 확인, 상수 변수 설정, 유틸 함수를 제공하는 class를 만들 수 있다.

4. final 제어자는 const와 비슷한 의미를 가지며, class, method, 멤버 변수, 지역 변수에 '변경될 수 없게' 적용시킨다.

5.  abstract 제어자는 선언부만 존재하고 그 안의 수행 내용은 구현되지 않은 추상 method를 선언할 때 사용된다.

**Comment by HYEOK9** [comment]
- Java는 C++과 달리 멤버 변수, 함수마다 public, private을 써주어야함. 같은 package에 있다면 import하지 않아도됨.
- `Player(Player p) { this(p.userName, p.healthPoint, p.attackPoint); }`와 같이 복사생성자 구현
- static(정적 멤버) : 클래스에 할당된 멤버. gc가 관여하지 않음.
- final : C에서 const와 비슷한 개념. 단, const는 컴파일중 결정되지만 final은 run time에 결정. final 붙은 class는 상속도 안됨.
- initializaiton block : 
1. class initialization block - class가 로딩될 때 한 번만 호출. static { a=1;}과 같이 사용
2. instance initialization block - instance가 생성될 때 마다 호출. {b=2;}와 같이 사용

**Comment by splguyjr** [comment]
-c++과 다르게 java는 멤버 함수,변수 하나하나에 private, public을 적용
-생성자는 안만들시에 기본생성자, 작성했을시에 this를 이용해 재사용가능
-제어자는 클래스, 변수 또는 메서드의 선언부에 부가적인 의미를 부여
-static:클래스 메모리에 있는 변수(생성된 인스턴스 갯수 확인 등에 사용)
-final: 변경 불가능하게 만듬
 클래스: 변경 확장x 조상 클래스x
 메서드: 변경 x 파생 클래스에서 오버라이딩 불가
  상수앞에 붙으면 값 변경 불가
-abstract: 메서드의 선언부만 작성하고 실제 수행 내용은 구현x, 인스턴스 생성 불가하며 추상 클래스의 파생 클래스에서 오버라이딩해야 사용가능
-접근제어자: private, protected,default,public
-static: 클래스 초기화 블럭과 인스턴스 초기화블럭으로 나누어 작성하는 식으로 사용. 이때 클래스 초기화 블럭은 클래스가 메모리에 처음 로딩될 때 한번만 실행됨
